/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javierbs.interfaces.practica1_javierbernardo.entidades.Compania;
import modelos.TablaCompAereas;

/**
 *
 * @author javierbs
 */
public class FrmCompAereas extends javax.swing.JFrame {
    TablaCompAereas modelo = new TablaCompAereas();
    /**
     * Creates new form FrmCompAereas
     */
    public FrmCompAereas() {
        initComponents();
        visualizarCompanias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearComp = new javax.swing.JButton();
        btnEliminarComp = new javax.swing.JButton();
        btnEditarComp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompanias = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearComp.setText("Dar de alta");
        btnCrearComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCompActionPerformed(evt);
            }
        });

        btnEliminarComp.setText("Dar de baja");
        btnEliminarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCompActionPerformed(evt);
            }
        });

        btnEditarComp.setText("Editar");
        btnEditarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCompActionPerformed(evt);
            }
        });

        tblCompanias.setModel(modelo);
        jScrollPane1.setViewportView(tblCompanias);

        lblError.setToolTipText("lblError");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnCrearComp)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnEliminarComp)
                                .addGap(104, 104, 104)
                                .addComponent(btnEditarComp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(btnVolver))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearComp)
                    .addComponent(btnEliminarComp)
                    .addComponent(btnEditarComp)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCompActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompaniaAlta(FrmCompAereas.this).setVisible(true);
                
            }
        });
    }//GEN-LAST:event_btnCrearCompActionPerformed

    private void btnEliminarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCompActionPerformed
        int indiceTabla = tblCompanias.getSelectedRow();
        if(indiceTabla == -1){
            lblError.setText("Debe seleccionar una compañía");
        }else{
            Object prefijoObjeto = tblCompanias.getValueAt(indiceTabla, 0);
            int prefijo = Integer.parseInt(prefijoObjeto.toString());
            String codigo = tblCompanias.getValueAt(indiceTabla, 1).toString();
            String nombre = tblCompanias.getValueAt(indiceTabla, 2).toString();
            String direccion = tblCompanias.getValueAt(indiceTabla, 3).toString();
            String municipio = tblCompanias.getValueAt(indiceTabla, 4).toString();
            String telPasajero = tblCompanias.getValueAt(indiceTabla, 5).toString();
            String telAeropuerto = tblCompanias.getValueAt(indiceTabla, 6).toString();
            Compania compania = new Compania(prefijo, codigo, nombre, direccion, municipio, telPasajero, telAeropuerto);
            Compania.eliminarCompania(compania);
            visualizarCompanias();
        }
    }//GEN-LAST:event_btnEliminarCompActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEditarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCompActionPerformed
        int indiceTabla = tblCompanias.getSelectedRow();
        if(indiceTabla == -1){
            lblError.setText("Debe seleccionar una compañía");
        }else{
            Object prefijoObjeto = tblCompanias.getValueAt(indiceTabla, 0);
            int prefijo = Integer.parseInt(prefijoObjeto.toString());
            String codigo = tblCompanias.getValueAt(indiceTabla, 1).toString();
            String nombre = tblCompanias.getValueAt(indiceTabla, 2).toString();
            String direccion = tblCompanias.getValueAt(indiceTabla, 3).toString();
            String municipio = tblCompanias.getValueAt(indiceTabla, 4).toString();
            String telPasajero = tblCompanias.getValueAt(indiceTabla, 5).toString();
            String telAeropuerto = tblCompanias.getValueAt(indiceTabla, 6).toString();
            Compania compania = new Compania(prefijo, codigo, nombre, direccion, municipio, telPasajero, telAeropuerto);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompaniaEditar(FrmCompAereas.this, compania).setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnEditarCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompAereas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompAereas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompAereas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompAereas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCompAereas().setVisible(true);
            }
        });
    }
    
    public void visualizarCompanias(){       
        ArrayList<Compania> companias = new ArrayList<Compania>();
        companias = Compania.leerCompanias();
        modelo.setRowCount(companias.size());
        int fila = 0;
        for(Compania compania: companias){
            tblCompanias.getModel().setValueAt(compania.getPrefijo(), fila, 0);
            tblCompanias.getModel().setValueAt(compania.getCodigo(), fila, 1);
            tblCompanias.getModel().setValueAt(compania.getNombre(), fila, 2);
            tblCompanias.getModel().setValueAt(compania.getDireccion(), fila, 3);
            tblCompanias.getModel().setValueAt(compania.getMunicipio(), fila, 4);
            tblCompanias.getModel().setValueAt(compania.getTelPasajero(), fila, 5);
            tblCompanias.getModel().setValueAt(compania.getTelAeropuerto(), fila, 6);
            fila++;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearComp;
    private javax.swing.JButton btnEditarComp;
    private javax.swing.JButton btnEliminarComp;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tblCompanias;
    // End of variables declaration//GEN-END:variables
}
