/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javierbs.interfaces.practica1_javierbernardo.entidades.Aeropuerto;
import javierbs.interfaces.practica1_javierbernardo.entidades.Validacion;
import javierbs.interfaces.practica1_javierbernardo.entidades.Vuelo;
import javierbs.interfaces.practica1_javierbernardo.entidades.VueloDiario;
import modelos.TablaVuelosDiarios;

/**
 *
 * @author Usuario
 */
public class FrmVuelosDiarios extends javax.swing.JFrame {
    TablaVuelosDiarios modelo = new TablaVuelosDiarios();

    /**
     * Creates new form FrmVuelosDiarios
     */
    public FrmVuelosDiarios() {
        initComponents();
        visualizarVuelosDiarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelosDiarios = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVuelosDiarios.setModel(modelo);
        jScrollPane1.setViewportView(tblVuelosDiarios);

        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAlta)
                        .addGap(90, 90, 90)
                        .addComponent(btnBaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(109, 109, 109)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(btnVolver))
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueloDiarioAlta(FrmVuelosDiarios.this).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int indiceTabla = tblVuelosDiarios.getSelectedRow();
        if(indiceTabla == -1){
            lblError.setText("Debe seleccionar un vuelo");
        }else{
            String codigo = tblVuelosDiarios.getValueAt(indiceTabla, 0).toString();
            String fechaSt = tblVuelosDiarios.getValueAt(indiceTabla, 1).toString();
            LocalDate fecha = Validacion.parsearFecha(fechaSt);
            String hSalidaSt = tblVuelosDiarios.getValueAt(indiceTabla, 2).toString();
            LocalTime hSalida = Validacion.parsearHora(hSalidaSt);
            String hLlegadaSt = tblVuelosDiarios.getValueAt(indiceTabla, 3).toString();
            LocalTime hLlegada = Validacion.parsearHora(hLlegadaSt);
            String nPlazasOcupadasSt = tblVuelosDiarios.getValueAt(indiceTabla, 4).toString();
            int nPlazasOcupadas = Integer.parseInt(nPlazasOcupadasSt);
            String precioSt = tblVuelosDiarios.getValueAt(indiceTabla, 5).toString();
            double precio = Double.parseDouble(precioSt);
            VueloDiario vueloDiario = new VueloDiario(codigo, fecha, hSalida, hLlegada, nPlazasOcupadas, precio);
            vueloDiario.eliminarVueloDiario();
            visualizarVuelosDiarios();
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indiceTabla = tblVuelosDiarios.getSelectedRow();
        if (indiceTabla == -1) {
            lblError.setText("Debe seleccionar un vuelo diario");
        } else {
            String codigo = tblVuelosDiarios.getValueAt(indiceTabla, 0).toString();
            String fechaSt = tblVuelosDiarios.getValueAt(indiceTabla, 1).toString();
            LocalDate fecha = Validacion.parsearFecha(fechaSt);
            String hSalidaSt = tblVuelosDiarios.getValueAt(indiceTabla, 2).toString();
            LocalTime hSalida = Validacion.parsearHora(hSalidaSt);
            String hLlegadaSt = tblVuelosDiarios.getValueAt(indiceTabla, 3).toString();
            LocalTime hLlegada = Validacion.parsearHora(hLlegadaSt);
            String nPlazasOcupadasSt = tblVuelosDiarios.getValueAt(indiceTabla, 4).toString();
            int nPlazasOcupadas = Integer.parseInt(nPlazasOcupadasSt);
            String precioSt = tblVuelosDiarios.getValueAt(indiceTabla, 5).toString();
            double precio = Double.parseDouble(precioSt);
            VueloDiario vueloDiario = new VueloDiario(codigo, fecha, hSalida, hLlegada, nPlazasOcupadas, precio);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueloDiarioEditar(FrmVuelosDiarios.this, vueloDiario).setVisible(true);
            }
        });
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

  
    public void visualizarVuelosDiarios(){
        ArrayList<VueloDiario> vuelosDiarios = VueloDiario.leerVuelosDiarios();
        modelo.setRowCount(vuelosDiarios.size());
        int fila = 0;
        for(VueloDiario vd: vuelosDiarios){
            tblVuelosDiarios.getModel().setValueAt(vd.getVuelo(), fila, 0);
            String fecha = Validacion.parsearFechaAString(vd.getFecha());
            tblVuelosDiarios.getModel().setValueAt(fecha, fila, 1);
            tblVuelosDiarios.getModel().setValueAt(vd.gethSalida(), fila, 2);
            tblVuelosDiarios.getModel().setValueAt(vd.gethLlegada(), fila, 3);
            tblVuelosDiarios.getModel().setValueAt(vd.getnPlazasOcupadas(), fila, 4);
            tblVuelosDiarios.getModel().setValueAt(vd.getPrecioVuelo(), fila, 5);
            fila++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tblVuelosDiarios;
    // End of variables declaration//GEN-END:variables
}
