/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.time.LocalDate;
import java.time.LocalTime;
import javierbs.interfaces.practica1_javierbernardo.entidades.Validacion;
import javierbs.interfaces.practica1_javierbernardo.entidades.Vuelo;
import javierbs.interfaces.practica1_javierbernardo.entidades.VueloDiario;

/**
 *
 * @author javierbs
 */
public class VueloDiarioEditar extends javax.swing.JFrame {

    FrmVuelosDiarios frmVuelosDiarios;
    VueloDiario vueloDiario;
    String codVuelo;
    String fechaVuelo;
    
    public VueloDiarioEditar(FrmVuelosDiarios frmVuelosDiarios, VueloDiario vueloDiario) {
        initComponents();
        this.frmVuelosDiarios = frmVuelosDiarios;
        this.vueloDiario = vueloDiario;
        this.codVuelo = vueloDiario.getVuelo();
        this.fechaVuelo = Validacion.parsearFechaAString(vueloDiario.getFecha());
        rellenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHSalida = new javax.swing.JTextField();
        txtHLlegada = new javax.swing.JTextField();
        txtNPlazasOcupadas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("N. pl. ocupadas");

        jLabel7.setText("dd/mm/yyyy");

        jLabel6.setText("Precio");

        jLabel1.setText("Código");

        jLabel2.setText("Fecha");

        btnAlta.setText("Editar");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        jLabel3.setText("H. Salida");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel4.setText("H. Llegada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigo)
                    .addComponent(txtFecha)
                    .addComponent(txtHSalida)
                    .addComponent(txtHLlegada)
                    .addComponent(txtNPlazasOcupadas)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlta)
                            .addComponent(btnVolver)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtNPlazasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        boolean compForm = true;
        lblError.setText("");
        int nPlazasOcupadas = 0;
        Vuelo vuelo;
        if (txtCodigo.getText().isBlank() || txtFecha.getText().isBlank()
                || txtHSalida.getText().isBlank() || txtHLlegada.getText().isBlank()
                || txtNPlazasOcupadas.getText().isBlank() || txtPrecio.getText().isBlank()) {
            compForm = false;
            lblError.setText("Tiene que rellenar todos los campos");
        } else {
            if (!Vuelo.existeCodigo(txtCodigo.getText().toString())) {
                compForm = false;
                lblError.setText("El código de vuelo no existe");
            } else {
                vuelo = Vuelo.leerPorCodigo(txtCodigo.getText().toString());
                if (!Validacion.validarFecha(txtFecha.getText().toString())) {
                    compForm = false;
                    lblError.setText("Fecha no válida");
                } else {
                    if (VueloDiario.existeVueloDiarioId(txtCodigo.getText(), txtFecha.getText(), codVuelo, fechaVuelo)) {
                        compForm = false;
                        lblError.setText("Este vuelo ya existe");
                    } else {
                        if (!Validacion.validarHora(txtHSalida.getText().toString())) {
                            compForm = false;
                            lblError.setText("Hora de salida no válida");
                        }
                        if (!Validacion.validarHora(txtHLlegada.getText().toString())) {
                            compForm = false;
                            lblError.setText("Hora de llegada no válida");
                        }
                        if (!Validacion.esNumero(txtNPlazasOcupadas.getText().toString())) {
                            compForm = false;
                            lblError.setText("El número de plazas ocupadas debe de ser un número");
                        } else {
                            nPlazasOcupadas = Integer.parseInt(txtNPlazasOcupadas.getText().toString());
                            if (!VueloDiario.validarNPlazasOcupadas(nPlazasOcupadas, txtCodigo.getText().toString())) {
                                compForm = false;
                                lblError.setText("El número de plazas ocupadas tiene que ser menor al número de plazas totales");
                            }
                        }
                        if (!Validacion.esNumero(txtPrecio.getText().toString()) && !Validacion.esDouble(txtPrecio.getText().toString())) {
                            compForm = false;
                            lblError.setText("El precio tiene que ser un número");
                        }
                    }
                }
            }
        }
        if (compForm) {
            String codigo = txtCodigo.getText().toString();
            String fechaSt = txtFecha.getText().toString();
            LocalDate fecha = Validacion.parsearFecha(fechaSt);
            String hSalidaSt = txtHSalida.getText().toString();
            LocalTime hSalida = Validacion.parsearHora(hSalidaSt);
            String hLlegadaSt = txtHLlegada.getText().toString();
            LocalTime hLlegada = Validacion.parsearHora(hLlegadaSt);
            String nPlazasOcupadasSt = txtNPlazasOcupadas.getText().toString();
            double precio = Double.parseDouble(txtPrecio.getText().toString());
            VueloDiario vueloDiario = new VueloDiario(codigo, fecha, hSalida, hLlegada, nPlazasOcupadas, precio);
            vueloDiario.editarVueloDiario(codVuelo, fechaVuelo);
            frmVuelosDiarios.visualizarVuelosDiarios();
            dispose();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void rellenarCampos(){
        txtCodigo.setText(vueloDiario.getVuelo());
        String fecha = Validacion.parsearFechaAString(vueloDiario.getFecha());
        txtFecha.setText(fecha);
        txtHSalida.setText(vueloDiario.gethSalida().toString());
        txtHLlegada.setText(vueloDiario.gethLlegada().toString());
        Integer nPlazasOcupadasInt = vueloDiario.getnPlazasOcupadas();
        String nPlazasOcupadas = nPlazasOcupadasInt.toString();
        txtNPlazasOcupadas.setText(nPlazasOcupadas);
        Double precioDbl = vueloDiario.getPrecioVuelo();
        String precio = precioDbl.toString();
        txtPrecio.setText(precio);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHLlegada;
    private javax.swing.JTextField txtHSalida;
    private javax.swing.JTextField txtNPlazasOcupadas;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
