/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javierbs.interfaces.practica1_javierbernardo.entidades.Aeropuerto;
import javierbs.interfaces.practica1_javierbernardo.entidades.Validacion;
import javierbs.interfaces.practica1_javierbernardo.entidades.Vuelo;

/**
 *
 * @author Usuario
 */
public class VueloAlta extends javax.swing.JFrame {

    FrmVuelos frmVuelos;

    public VueloAlta(FrmVuelos frmVuelos) {
        initComponents();
        this.frmVuelos = frmVuelos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtAOrigen = new javax.swing.JTextField();
        txtADestino = new javax.swing.JTextField();
        txtNPlazas = new javax.swing.JTextField();
        txtHSalida = new javax.swing.JTextField();
        txtHLlegada = new javax.swing.JTextField();
        txtDiasOpera = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Aer. Origen");

        jLabel3.setText("Aer. Destino");

        jLabel4.setText("N. Plazas");

        jLabel5.setText("H. Salida");

        jLabel6.setText("H. Llegada");

        jLabel7.setText("Días que opera");

        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiasOpera, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(btnVolver)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtADestino, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnAlta)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtADestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiasOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
       boolean compForm = true;
        lblError.setText("");
        if (txtCodigo.getText().isBlank() || txtAOrigen.getText().isBlank()
            || txtADestino.getText().isBlank() || txtNPlazas.getText().isBlank()
            || txtHSalida.getText().isBlank() || txtHLlegada.getText().isBlank()
            || txtDiasOpera.getText().isBlank()) {
            compForm = false;
            lblError.setText("Tiene que rellenar todos los campos");
        } else {
            if (!Vuelo.validarCodigo(txtCodigo.getText().toString())) {
                compForm = false;
                lblError.setText("El código de vuelo es inválido");
            }
            if (!Validacion.esNumero(txtNPlazas.getText().toString())) {
                compForm = false;
                lblError.setText("El campo N. Plazas tiene que ser un número");
            }
            if (!Validacion.sonDiasOperables(txtDiasOpera.getText().toString())) {
                compForm = false;
                lblError.setText("El campo Dias que opera es inválido");
            }
            if (!Aeropuerto.validarCodigo(txtAOrigen.getText().toString())) {
                compForm = false;
                lblError.setText("El codigo del aeropuerto de origen no existe");
            }
            if (!Aeropuerto.validarCodigo(txtADestino.getText().toString())) {
                compForm = false;
                lblError.setText("El codigo del aeropuerto de destino no existe");
            }
            if (!Validacion.validarHora(txtHSalida.getText().toString())
                || !Validacion.validarHora(txtHLlegada.getText().toString())) {
                compForm = false;
                lblError.setText("La hora es inválida");
            }
        }

        if (compForm) {
            Aeropuerto aOrigen = Aeropuerto.leerPorCodigo(txtAOrigen.getText().toString());
            Aeropuerto aDestino = Aeropuerto.leerPorCodigo(txtADestino.getText().toString());
            Integer nPlazas = Integer.parseInt(txtNPlazas.getText().toString());
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime hSalida = LocalTime.parse(txtHSalida.getText().toString(), formato);
            LocalTime hLlegada = LocalTime.parse(txtHLlegada.getText().toString(), formato);
            Vuelo vuelo = new Vuelo(txtCodigo.getText().toString(), aOrigen, aDestino, nPlazas, hSalida, hLlegada, txtDiasOpera.getText().toString());
            vuelo.introducirVuelo();
            vaciarFormulario();
            frmVuelos.visualizarVuelos();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void vaciarFormulario() {
        txtCodigo.setText("");
        txtAOrigen.setText("");
        txtADestino.setText("");
        txtNPlazas.setText("");
        txtHSalida.setText("");
        txtHLlegada.setText("");
        txtDiasOpera.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtADestino;
    private javax.swing.JTextField txtAOrigen;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDiasOpera;
    private javax.swing.JTextField txtHLlegada;
    private javax.swing.JTextField txtHSalida;
    private javax.swing.JTextField txtNPlazas;
    // End of variables declaration//GEN-END:variables
}
